name: ScreenShare
version: 1.0
main: dev.haxmc.screenShare.ScreenShare
api-version: 1.16

commands:
  sprawdz:
    description: Start a screen share check.
    usage: /sprawdz <player>

  ss:
    description: Alias for /sprawdz
    usage: /ss <player>

  check:
    description: Alias for /sprawdz
    usage: /check <player>

  przyznajesie:
    description: Admit to cheating.
    usage: /przyznajesie

  admit:
    description: Alias for /przyznajesie
    usage: /admit

  przyznaj:
    description: Alias for /przyznajesie
    usage: /przyznaj
